stages:
  - build
  - deploy

variables:
  AZURE_WEBAPP_NAME: "your-webapp-name"
  AZURE_RESOURCE_GROUP: "your-resource-group"
  DOTNET_VERSION: "8.0"

before_script:
  - apt-get update && apt-get install -y unzip
  - export PATH="$PATH:$HOME/.dotnet/tools"

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet publish -c Release -o out
  artifacts:
    paths:
      - out/

deploy:
  stage: deploy
  script:
    - az login --service-principal -u $AZURE_USERNAME -p $AZURE_PASSWORD --tenant $AZURE_TENANT
    - az webapp deployment source config-zip --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --src out/
  only:
    - main
